version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: forsen123
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ./postgres/init-products.sql:/docker-entrypoint-initdb.d/init-products.sql
      - ./postgres/init-users.sql:/docker-entrypoint-initdb.d/init-users.sql
    networks:
      - spring-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      default_zone: http://eureka-server:8761/eureka/
    depends_on:
      product-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
      eureka-server:
        condition: service_started   
    networks:
      - spring-cloud
      - spring-front

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    restart: always
    networks:
      - spring-cloud

  user-service:
    build: ./user-service
    restart: always
    environment:
      POSTGRES_CONN: jdbc:postgresql://postgres:5432/users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: forsen123
      default_zone: http://eureka-server:8761/eureka/
      host_name: user-service
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - spring-cloud
      - spring-db
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:8080/actuator/health || exit 1"]
      interval: 1m
      timeout: 30s
      retries: 3

  product-service:
    build: ./product-service
    restart: always
    environment:
      POSTGRES_CONN: jdbc:postgresql://postgres:5432/products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: forsen123
      default_zone: http://eureka-server:8761/eureka/
      host_name: product-service
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - spring-cloud
      - spring-db
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:8080/actuator/health || exit 1"]
      interval: 1m
      timeout: 30s
      retries: 3

  product-front:
    build: ./product-front
    restart: always
    networks:
      - spring-front

  user-front:
    build: ./user-front
    restart: always
    networks:
      - spring-front

  shell-app-front:
    build: ./shell-app-front
    restart: always
    networks:
      - spring-front

  nginx-reverse-proxy:
    build: ./nginx-server
    restart: always
    depends_on:
      - user-front
      - product-front
      - shell-app-front
      - api-gateway
    ports:
      - "80:80"
    networks:
      - spring-front
networks:
  spring-db:
  spring-cloud:
  spring-front:
volumes:
  pg_data: